
import java.awt.*;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Titesh
 */
public class MyContacts extends javax.swing.JFrame {

    /**
     * Creates new form MyContacts
     */
    String imagepth = null; 
    public static  int currentUserId;
    int pos = 0;
    public MyContacts() {
        initComponents();
        populateJtable();
        displaytable();
        
        jTable2.setShowGrid(true);
        jTable2.setGridColor(Color.yellow);
        jTable2.setSelectionBackground(Color.gray);
        
        JTableHeader th = jTable2.getTableHeader();
        th.setForeground(Color.BLUE);
        
        th.setFont(new Font("Tahoma", Font.PLAIN, 14));
         System.out.println(currentUserId+ "From Contact");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelUserPic = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldFname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldLname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelContactPic = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAddress = new javax.swing.JTextArea();
        jButtonBrowseImage = new javax.swing.JButton();
        jComboBoxGroup = new javax.swing.JComboBox();
        jButtonAddCantact1 = new javax.swing.JButton();
        jTextFieldId = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButtonLast = new javax.swing.JButton();
        jButtonFirst = new javax.swing.JButton();
        jButtonPrevious = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(17, 169, 81));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("x");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("-");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("My Contacts");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabelUserPic.setBackground(new java.awt.Color(255, 255, 0));
        jLabelUserPic.setOpaque(true);

        jLabelUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(0, 0, 255));
        jLabelUsername.setText("UserName");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("-");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabelUserPic, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 527, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelUserPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 60));

        jPanel6.setBackground(new java.awt.Color(35, 92, 191));
        jPanel6.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Address:");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(490, 140, 100, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Phone:");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(50, 170, 100, 30);

        jTextFieldEmail.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(0, 0, 204));
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        jPanel6.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(160, 220, 230, 30);

        jTextFieldPhone.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldPhone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldPhone.setForeground(new java.awt.Color(0, 0, 204));
        jTextFieldPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneActionPerformed(evt);
            }
        });
        jPanel6.add(jTextFieldPhone);
        jTextFieldPhone.setBounds(160, 170, 230, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("First Name:");
        jPanel6.add(jLabel9);
        jLabel9.setBounds(40, 70, 110, 30);

        jTextFieldFname.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldFname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldFname.setForeground(new java.awt.Color(0, 0, 204));
        jTextFieldFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFnameActionPerformed(evt);
            }
        });
        jPanel6.add(jTextFieldFname);
        jTextFieldFname.setBounds(160, 70, 230, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Last Name:");
        jPanel6.add(jLabel10);
        jLabel10.setBounds(40, 120, 110, 30);

        jTextFieldLname.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldLname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldLname.setForeground(new java.awt.Color(0, 0, 204));
        jTextFieldLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLnameActionPerformed(evt);
            }
        });
        jPanel6.add(jTextFieldLname);
        jTextFieldLname.setBounds(160, 120, 230, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Email:");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(50, 220, 100, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel6.add(jSeparator1);
        jSeparator1.setBounds(440, 30, 10, 230);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Group:");
        jPanel6.add(jLabel12);
        jLabel12.setBounds(50, 270, 100, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Profile Picture:");
        jPanel6.add(jLabel13);
        jLabel13.setBounds(460, 30, 150, 30);

        jLabelContactPic.setBackground(new java.awt.Color(204, 255, 255));
        jLabelContactPic.setOpaque(true);
        jPanel6.add(jLabelContactPic);
        jLabelContactPic.setBounds(610, 30, 150, 100);

        jTextAreaAddress.setBackground(new java.awt.Color(228, 241, 254));
        jTextAreaAddress.setColumns(20);
        jTextAreaAddress.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAddress);

        jPanel6.add(jScrollPane1);
        jScrollPane1.setBounds(610, 140, 340, 90);

        jButtonBrowseImage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonBrowseImage.setText("Browse");
        jButtonBrowseImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBrowseImageMouseClicked(evt);
            }
        });
        jButtonBrowseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseImageActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonBrowseImage);
        jButtonBrowseImage.setBounds(790, 80, 80, 30);

        jComboBoxGroup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Family", "Friends", "Work", " " }));
        jPanel6.add(jComboBoxGroup);
        jComboBoxGroup.setBounds(160, 270, 230, 30);

        jButtonAddCantact1.setBackground(new java.awt.Color(38, 194, 129));
        jButtonAddCantact1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddCantact1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddCantact1.setText("Add");
        jButtonAddCantact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCantact1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonAddCantact1);
        jButtonAddCantact1.setBounds(840, 260, 100, 30);

        jTextFieldId.setEditable(false);
        jTextFieldId.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldId.setForeground(new java.awt.Color(0, 0, 204));
        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });
        jPanel6.add(jTextFieldId);
        jTextFieldId.setBounds(160, 20, 230, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("ID:");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(50, 20, 60, 30);

        jButtonLast.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonLast.setText(">>");
        jButtonLast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLastMouseClicked(evt);
            }
        });
        jButtonLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLastActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonLast);
        jButtonLast.setBounds(370, 330, 90, 30);

        jButtonFirst.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonFirst.setText("<<");
        jButtonFirst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFirstMouseClicked(evt);
            }
        });
        jButtonFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFirstActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonFirst);
        jButtonFirst.setBounds(60, 330, 90, 30);

        jButtonPrevious.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonPrevious.setText("<");
        jButtonPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPreviousMouseClicked(evt);
            }
        });
        jButtonPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviousActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonPrevious);
        jButtonPrevious.setBounds(160, 330, 90, 30);

        jButtonNext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonNext.setText(">");
        jButtonNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNextMouseClicked(evt);
            }
        });
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonNext);
        jButtonNext.setBounds(270, 330, 90, 30);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jPanel6.add(jScrollPane3);
        jScrollPane3.setBounds(10, 370, 1110, 330);

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 59, 1130, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void populateJtable(){
        
         contactQuery cq = new contactQuery();
         ArrayList<contact> ctList = cq.ContactList(currentUserId);
         
         String [] colNames ={"Id","First Name","Last Name","Group","Phone","Email","Address","Image"};
         Object[][] rows = new Object[ctList.size()][8];
         
         for(int i =0; i < ctList.size(); i++){
             rows[i][0] = ctList.get(i).getEid();
             rows[i][1] = ctList.get(i).getFname();
             rows[i][2] = ctList.get(i).getLname();
             rows[i][3] = ctList.get(i).getGroupc();
             rows[i][4] = ctList.get(i).getPhone();
             rows[i][5] = ctList.get(i).getEmail();
             rows[i][6] = ctList.get(i).getAddress();
             
             ImageIcon pic =new ImageIcon(new ImageIcon
                                         (ctList.get(i).getPic())
                                         .getImage()
                                         .getScaledInstance(120, 80, Image.SCALE_SMOOTH));
        rows[i][7] = pic;    
         } 
         MyModel mmd = new MyModel(rows, colNames);
         jTable2.setModel(mmd);
         jTable2.setRowHeight(80);
         jTable2.getColumnModel().getColumn(7).setPreferredWidth(120);  
    }
        private void displaytable(){
        
       
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =(com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/contact_application","root","");
            String sql="select * from my_contact";
            PreparedStatement ps=con.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
          
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
           
    }
    
    
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneActionPerformed

    private void jTextFieldFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFnameActionPerformed

    private void jTextFieldLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLnameActionPerformed

    private void jButtonBrowseImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBrowseImageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBrowseImageMouseClicked

    private void jButtonBrowseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseImageActionPerformed

        Myfunc mf =new Myfunc();
        imagepth =  mf.BrowseImage(jLabelContactPic);
        System.out.print(imagepth);

    }//GEN-LAST:event_jButtonBrowseImageActionPerformed

    private void jButtonAddCantact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCantact1ActionPerformed

        String fname = jTextFieldFname.getText();
        String lname = jTextFieldLname.getText();
        String phone = jTextFieldPhone.getText();
        String address =jTextAreaAddress.getText();
        String email = jTextFieldEmail.getText();
        String groupc = jComboBoxGroup.getSelectedItem().toString();
        
        
        // you can check if all fields are empty
        // but in this case [will only check if  the user select an image
        // and to do that we are going to use imagePath
        byte[] img =null;
        if(imagepth !=null) {
    
        try {
             
             Path pth = Paths.get(imagepth);
             img =Files.readAllBytes(pth);
              contact c = new contact(null, fname, lname, groupc, phone, email, address, img,0);
              contactQuery cq = new contactQuery();
              cq.insertContact(c);
              refreshJtable();
              clearFields();
        } catch (IOException ex) {
            Logger.getLogger(MyContacts.class.getName()).log(Level.SEVERE, null, ex);
        }
       }else{
            JOptionPane.showMessageDialog(null, "You Must Select A Profile Picture");
        }
      
    }//GEN-LAST:event_jButtonAddCantact1ActionPerformed

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdActionPerformed

    public void refreshJtable()
    {
        jTable2.setModel(new DefaultTableModel());
        populateJtable();
        
    }
    
    public void clearFields()
    {
        jTextFieldId.setText("");
        jTextFieldFname.setText("");
        jTextFieldLname.setText("");
        jTextFieldEmail.setText("");
        jTextFieldPhone.setText("");
        jTextAreaAddress.setText("");
        jComboBoxGroup.setSelectedIndex(0);
        jLabelContactPic.setIcon(null);
        //set imagePath to null to prevent  the user to add unwanted duplicate images
        imagepth =null;
    }
            
      private void showData(int index)
      {
        jTextFieldFname.setText(jTable2.getValueAt(index, 1).toString());
        jTextFieldLname.setText(jTable2.getValueAt(index, 2).toString());
        
        //group phone email address pic
        
        jComboBoxGroup.setSelectedItem(jTable2.getValueAt(index, 3));
        jTextFieldPhone.setText(jTable2.getValueAt(index, 4).toString());
        jTextFieldEmail.setText(jTable2.getValueAt(index, 5).toString());
        jTextFieldId.setText(jTable2.getValueAt(index, 0).toString());
        jTextAreaAddress.setText(jTable2.getValueAt(index, 6).toString());
        
        Image pic =((ImageIcon)jTable2.getValueAt(index, 7)).getImage().getScaledInstance(jLabelContactPic.getWidth(),jLabelContactPic.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon img = new ImageIcon(pic);
        
        jLabelContactPic.setIcon(img);
          
      }
               
    private void jButtonLastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLastMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLastMouseClicked

    private void jButtonLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLastActionPerformed
       pos = jTable2.getRowCount()-1;
       showData(pos);
    }//GEN-LAST:event_jButtonLastActionPerformed

    private void jButtonFirstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFirstMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFirstMouseClicked

    private void jButtonFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFirstActionPerformed
        pos =0; 
        showData(pos); 
    }//GEN-LAST:event_jButtonFirstActionPerformed

    private void jButtonPreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPreviousMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPreviousMouseClicked

    private void jButtonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousActionPerformed
       pos--;
       showData(pos);
    }//GEN-LAST:event_jButtonPreviousActionPerformed

    private void jButtonNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNextMouseClicked

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
      pos++;
      showData(pos);
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
       
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        model.addRow(new Object[]{jTextFieldFname.getText(),jTextFieldFname.getText(),jComboBoxGroup.getSelectedItem(),jTextFieldPhone.getText(),jTextFieldEmail.getText(),jTextAreaAddress.getText(),jLabelContactPic.getText()});
 
         int rowindex =jTable2.getSelectedRow();
        jTextFieldFname.setText(jTable2.getValueAt(rowindex, 1).toString());
        jTextFieldLname.setText(jTable2.getValueAt(rowindex, 2).toString());
        
        //group phone email address pic
        
        jComboBoxGroup.setSelectedItem(jTable2.getValueAt(rowindex, 3));
        jTextFieldPhone.setText(jTable2.getValueAt(rowindex, 4).toString());
        jTextFieldEmail.setText(jTable2.getValueAt(rowindex, 5).toString());
        jTextFieldId.setText(jTable2.getValueAt(rowindex, 0).toString());
        jTextAreaAddress.setText(jTable2.getValueAt(rowindex, 6).toString());
        
        Image pic =((ImageIcon)jTable2.getValueAt(rowindex, 7)).getImage().getScaledInstance(jLabelContactPic.getWidth(),jLabelContactPic.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon img = new ImageIcon(pic);
        
        jLabelContactPic.setIcon(img);
        jButtonAddCantact1.setEnabled(false);
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyContacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyContacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyContacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyContacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyContacts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCantact1;
    private javax.swing.JButton jButtonBrowseImage;
    private javax.swing.JButton jButtonFirst;
    private javax.swing.JButton jButtonLast;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JComboBox<String> jComboBoxGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelContactPic;
    public javax.swing.JLabel jLabelUserPic;
    public javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextAreaAddress;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFname;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldLname;
    private javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables
}
